hello:
    uri: /
    controller: Controller\HelloController
    httpMethod: [GET]
ville:
    uri: /lesvilles
    controller: Controller\VilleController
    httpMethod: [GET, POST]
paris:
    uri: /lesvilles/new
    controller: Controller\ParisController
    httpMethod: [GET]
resultat:
    uri: /lesvilles/resultat
    controller: Controller\ResultatController
    httpMethod: [GET, POST]
api_ville:
    uri: /api/ville
    controller: Controller\api\VilleController
    httpMethod: [GET, POST]
api_ville-detail:
    uri: '/api/ville/{id}'
    controller: Controller\api\VilleDetailController
    httpMethod: [GET]
villeupdate:
    uri: '/ville/{id}/update'
    controller: Controller\VilleUpdateController
    httpMethod: [GET, POST]
medecin:
    uri: /medecin
    controller: Controller\MedecinController
    httpMethod: [GET, POST]
