hello:
    uri: /
    controller: Controller\HelloController
    httpMethod: [GET]
ville:
    uri: /lesvilles
    controller: Controller\VilleController
    httpMethod: [GET, POST]
paris:
    uri: /lesvilles/new
    controller: Controller\ParisController
    httpMethod: [GET]
